language: java

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "IDG4OIJXsB1SsADKJyhJwne6BWfip22inBgHxCzdKoofDj+HTTkuL8pP+/xgZSia4Msz8VRkIYYkeLrnRp9n9QyZisGJGp+WRTlgBc+ugNoSeJoK4C1vyYqKmldmeTHw1vo2/IFggANpxSQx5gN76ee/gHn4tAFZPvw36dKKyPw="

addons:
  coverity_scan:
    project:
      name: "jonesd/udanax-gold2java"
      description: "Build submitted via Travis CI"
    notification_email: david@dgjones.info
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: coverity_scan
